// Фрагменты «сгенерированного ИИ кода» для окна вайбкодинга.
// Чисто декоративные: печатаются по мере прогресса задачи.

export const SNIPPETS = {
  db_cleanup: [
    'import psycopg, datetime as dt',
    '',
    'RETENTION_DAYS = 90',
    '',
    'def cleanup(conn):',
    '    cutoff = dt.datetime.utcnow() - dt.timedelta(days=RETENTION_DAYS)',
    '    with conn.cursor() as cur:',
    '        cur.execute("DELETE FROM chat_logs WHERE created_at < %s", (cutoff,))',
    '        cur.execute("VACUUM ANALYZE chat_logs")',
    '    log.info("freed %s rows", cur.rowcount)',
    '',
    'schedule.every().day.at("03:00").do(cleanup, pool.get())',
  ],
  response_cache: [
    "import { createClient } from 'redis';",
    "import { hash } from './utils/hash';",
    '',
    'const redis = createClient({ url: process.env.REDIS_URL });',
    '',
    'export async function cachedCompletion(prompt: string) {',
    '  const key = `llm:${hash(prompt)}`;',
    '  const hit = await redis.get(key);',
    '  if (hit) return JSON.parse(hit); // токены не тратим',
    '  const res = await llm.complete(prompt);',
    '  await redis.set(key, JSON.stringify(res), { EX: 86_400 });',
    '  return res;',
    '}',
  ],
  auto_reports: [
    'from jinja2 import Template',
    'from agents import analyst',
    '',
    'async def weekly_report(client_id: str) -> bytes:',
    '    metrics = await warehouse.fetch(client_id, days=7)',
    '    summary = await analyst.summarize(metrics, temperature=0.2)',
    '    html = Template(REPORT_TPL).render(m=metrics, s=summary)',
    '    pdf = await renderer.to_pdf(html)',
    '    await billing.charge(client_id, plan="reports")',
    '    return pdf',
  ],
  vector_db: [
    'from qdrant_client import QdrantClient',
    'from embeddings import embed',
    '',
    'db = QdrantClient(url=QDRANT_URL)',
    '',
    'def retrieve(query: str, k: int = 5) -> list[str]:',
    '    hits = db.search("kb", query_vector=embed(query), limit=k)',
    '    return [h.payload["text"] for h in hits]',
    '',
    'def answer(query: str) -> str:',
    '    context = "\\n".join(retrieve(query))',
    '    return llm(f"Отвечай ТОЛЬКО по контексту:\\n{context}\\n\\nQ: {query}")',
  ],
  guardrails: [
    'from safety import toxicity, pii, fact_check',
    '',
    'BLOCK = {"toxicity": 0.7, "pii": 0.5, "unsupported_claim": 0.6}',
    '',
    'def guard(output: str, sources: list[str]) -> str:',
    '    scores = {',
    '        "toxicity": toxicity(output),',
    '        "pii": pii(output),',
    '        "unsupported_claim": 1 - fact_check(output, sources),',
    '    }',
    '    if any(scores[k] > v for k, v in BLOCK.items()):',
    '        raise HallucinationBlocked(scores)',
    '    return output',
  ],
  ci_cd: [
    'name: ci',
    'on: [push, pull_request]',
    'jobs:',
    '  test:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - run: pip install -r requirements.txt',
    '      - run: ruff check . && mypy src/',
    '      - run: pytest -q --cov=src --cov-fail-under=80',
    '      - run: python evals/run.py --suite prompts --min-score 0.9',
  ],
  monitoring: [
    'receivers:',
    '  otlp: { protocols: { grpc: {} } }',
    'processors:',
    '  batch: {}',
    'exporters:',
    '  prometheus: { endpoint: "0.0.0.0:9464" }',
    'alerts:',
    '  - name: HallucinationRateHigh',
    '    expr: rate(llm_hallucinations_total[1h]) > 0.05',
    '    severity: page',
    '  - name: TokenSpendSpike',
    '    expr: increase(llm_tokens_cost_usd[1h]) > 200',
  ],
  api_marketplace: [
    'package gateway',
    '',
    'func (g *Gateway) Handle(w http.ResponseWriter, r *http.Request) {',
    '\tkey := r.Header.Get("X-API-Key")',
    '\tplan, err := g.billing.Plan(key)',
    '\tif err != nil { http.Error(w, "unauthorized", 401); return }',
    '\tif !g.limiter.Allow(key, plan.RPM) { http.Error(w, "rate limit", 429); return }',
    '\tres := g.agents.Route(r.Context(), r.Body)',
    '\tg.billing.Meter(key, res.Tokens)',
    '\tjson.NewEncoder(w).Encode(res)',
    '}',
  ],
  temp_autopilot: [
    'class TemperatureAutopilot:',
    '    STEP = 0.15',
    '',
    '    def on_incident(self, agent, incident):',
    '        agent.temperature = max(0.1, agent.temperature - self.STEP)',
    '        if len(agent.system_prompt) < 2500:',
    '            agent.system_prompt += RULES_FROM(incident)',
    '        audit.log("autopilot", agent.id, agent.temperature)',
    '',
    '    def on_hour(self, agent, stats):',
    '        if stats.error_rate < 0.005 and agent.temperature < 0.6:',
    '            agent.temperature += 0.02  # осторожно возвращаем креатив',
  ],
  autoscaler: [
    'resource "gpu_pool" "agents" {',
    '  min_nodes = 1',
    '  max_nodes = 64',
    '',
    '  scaling_policy {',
    '    metric       = "tflops_utilization"',
    '    target_value = 0.8',
    '    scale_out_at = 0.92',
    '    cooldown     = "1h"',
    '  }',
    '}',
  ],
  auto_refactor: [
    "import { analyzeDebt, planRefactor } from './debt';",
    '',
    'cron.schedule("0 * * * *", async () => {',
    '  const debt = await analyzeDebt(repo);',
    '  if (debt.score < 45) return;',
    '  const plan = await planRefactor(debt, { model: "reasoning" });',
    '  const pr = await agent.apply(plan);',
    '  await ci.waitGreen(pr);',
    '  await pr.merge({ strategy: "squash" });',
    '  metrics.inc("self_healing_runs");',
    '});',
  ],
  refactor: [
    '$ vibe clean --deep',
    '→ сканирую 1 284 файла…',
    '→ найдено: 37 дублей промтов, 12 мёртвых эндпоинтов',
    '→ склеиваю одинаковые system prompts в шаблоны',
    '→ выпиливаю ретраи без backoff (жгли токены)',
    '→ удаляю закомментированный код 2024 года',
    '→ обновляю типы и тесты',
    '→ прогоняю эвалы промтов: 0.94 ✓',
    '→ открываю PR #' + Math.floor(100 + Math.random() * 900) + ': "chore: vibe clean"',
    '✔ тех-долг снижен',
  ],
};
