/**
 * Демо-набор для знакомства с приложением. Загружается только по явной
 * кнопке в настройках и полностью заменяет текущие данные.
 *
 * Набор специально устроен так, чтобы карта подсветила каждый класс проблем,
 * включая контрольный кейс из Definition of Done: критичный сервис,
 * чьё восстановление ведёт на мусорную почту.
 */
import type { VaultData } from '../types'

export function demoVault(): VaultData {
  return {
    version: 1,
    identities: [
      {
        id: 'i-bank-mail',
        label: 'Банковская',
        kind: 'email',
        value: 'e.sokolov.fin@yandex.ru',
        isAlias: false,
        createdAt: '2019-03-12',
        status: 'active',
      },
      {
        id: 'i-public-mail',
        label: 'Публичная',
        kind: 'email',
        value: 'egor.sokolov@gmail.com',
        isAlias: false,
        createdAt: '2014-06-01',
        status: 'active',
      },
      {
        id: 'i-trash-mail',
        label: 'Мусорная',
        kind: 'email',
        value: 'sokolov.promo@mail.ru',
        isAlias: false,
        createdAt: '2020-11-05',
        status: 'active',
      },
      {
        id: 'i-ozon-alias',
        label: 'Алиас для Ozon',
        kind: 'email',
        value: 'egor.sokolov+ozon@gmail.com',
        isAlias: true,
        createdAt: '2023-02-18',
        status: 'active',
      },
      {
        id: 'i-old-mail',
        label: 'Старая почта',
        kind: 'email',
        value: 'egorka1994@rambler.ru',
        isAlias: false,
        createdAt: '2009-09-01',
        status: 'compromised',
      },
      {
        id: 'i-main-phone',
        label: 'Основной номер',
        kind: 'phone',
        value: '+7 921 000-11-22',
        isAlias: false,
        createdAt: '2012-01-01',
        status: 'active',
      },
      {
        id: 'i-virtual-phone',
        label: 'Виртуальный номер',
        kind: 'phone',
        value: '+7 958 555-77-88',
        isAlias: true,
        createdAt: '2024-04-02',
        status: 'active',
      },
    ],
    services: [
      {
        id: 's-yandex',
        name: 'Яндекс Почта',
        domain: 'yandex.ru',
        category: 'почта',
        emailId: 'i-bank-mail',
        phoneId: 'i-main-phone',
        recoveryPhoneId: 'i-main-phone',
        registeredAt: '2019-03-12',
        dataGiven: ['fio'],
        twoFactor: 'totp',
        criticality: 'critical',
        status: 'active',
        notes: 'Держит банковскую почту — фундамент всей схемы.',
      },
      {
        id: 's-gmail',
        name: 'Gmail',
        domain: 'gmail.com',
        category: 'почта',
        emailId: 'i-public-mail',
        recoveryEmailId: 'i-trash-mail',
        registeredAt: '2014-06-01',
        dataGiven: ['fio'],
        twoFactor: 'passkey',
        criticality: 'critical',
        status: 'active',
        notes: 'Восстановление до сих пор смотрит на promo-ящик — кейс из DoD.',
      },
      {
        id: 's-bank',
        name: 'Северный Банк',
        domain: 'sevbank.ru',
        category: 'банк',
        emailId: 'i-bank-mail',
        phoneId: 'i-main-phone',
        recoveryEmailId: 'i-bank-mail',
        recoveryPhoneId: 'i-main-phone',
        registeredAt: '2019-04-01',
        dataGiven: ['fio', 'passport', 'card'],
        twoFactor: 'sms',
        criticality: 'critical',
        status: 'active',
        notes: 'SMS вместо TOTP — банк другого не умеет. Кандидат на ревизию.',
      },
      {
        id: 's-gosuslugi',
        name: 'Госуслуги',
        domain: 'gosuslugi.ru',
        category: 'госуслуги',
        emailId: 'i-public-mail',
        phoneId: 'i-main-phone',
        registeredAt: '2016-02-10',
        dataGiven: ['fio', 'passport', 'address'],
        twoFactor: 'totp',
        criticality: 'critical',
        status: 'active',
        notes: 'Заведён на публичную почту — карта это подсветит.',
      },
      {
        id: 's-avito',
        name: 'Авито',
        domain: 'avito.ru',
        category: 'маркетплейс',
        emailId: 'i-public-mail',
        phoneId: 'i-main-phone',
        registeredAt: '2018-09-01',
        dataGiven: ['fio', 'geo'],
        twoFactor: 'sms',
        criticality: 'normal',
        status: 'active',
      },
      {
        id: 's-kinopoisk',
        name: 'Кинопоиск',
        domain: 'kinopoisk.ru',
        category: 'развлечения',
        emailId: 'i-public-mail',
        registeredAt: '2017-05-11',
        dataGiven: ['card'],
        twoFactor: 'none',
        criticality: 'normal',
        status: 'active',
      },
      {
        id: 's-ozon',
        name: 'Ozon',
        domain: 'ozon.ru',
        category: 'маркетплейс',
        emailId: 'i-ozon-alias',
        phoneId: 'i-main-phone',
        registeredAt: '2023-02-18',
        dataGiven: ['fio', 'address', 'card'],
        twoFactor: 'sms',
        criticality: 'normal',
        status: 'active',
      },
      {
        id: 's-samokat',
        name: 'Самокат',
        domain: 'samokat.ru',
        category: 'доставка',
        emailId: 'i-trash-mail',
        phoneId: 'i-virtual-phone',
        registeredAt: '2024-05-20',
        dataGiven: ['address', 'geo'],
        twoFactor: 'none',
        criticality: 'disposable',
        status: 'active',
      },
      {
        id: 's-pikabu',
        name: 'Пикабу',
        domain: 'pikabu.ru',
        category: 'соцсеть',
        emailId: 'i-trash-mail',
        registeredAt: '2021-08-14',
        dataGiven: [],
        twoFactor: 'none',
        criticality: 'disposable',
        status: 'deletion-requested',
        notes: 'Заявка на удаление отправлена, подтверждения не было.',
      },
      {
        id: 's-oldforum',
        name: 'Форум аквариумистов',
        domain: 'aqa-forum.ru',
        category: 'форум',
        emailId: 'i-old-mail',
        registeredAt: '2011-03-03',
        dataGiven: ['fio'],
        twoFactor: 'none',
        criticality: 'disposable',
        status: 'active',
        notes: 'Почта в утечках, пароль там был везде одинаковый. Похоронить.',
      },
    ],
    events: [
      {
        id: 'e-spam-ozon',
        identityId: 'i-ozon-alias',
        type: 'spam',
        date: '2026-07-28',
        note: 'Спам про «инвестиции» на алиас +ozon — адрес знал только Ozon.',
      },
      {
        id: 'e-leak-ozon',
        serviceId: 's-ozon',
        identityId: 'i-ozon-alias',
        type: 'leak-suspected',
        date: '2026-07-28',
        note: 'Помечен по спаму на персональный алиас.',
      },
      {
        id: 'e-breach-rambler',
        identityId: 'i-old-mail',
        type: 'breach-confirmed',
        date: '2024-12-02',
        note: 'Адрес и старый пароль найдены в публичном дампе.',
      },
      {
        id: 'e-review-gosuslugi',
        serviceId: 's-gosuslugi',
        type: 'reviewed',
        date: '2026-01-15',
        note: 'Включён TOTP вместо SMS, сессии сброшены.',
      },
    ],
  }
}
