import {
  Atom,
  BadgeDollarSign,
  BatteryCharging,
  Bot,
  BrainCircuit,
  Bug,
  CloudLightning,
  Cpu,
  Crown,
  Fingerprint,
  Ghost,
  Handshake,
  Landmark,
  Layers,
  Network,
  Orbit,
  Percent,
  Pickaxe,
  Radiation,
  Receipt,
  Rocket,
  Satellite,
  Server,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Sun,
  Swords,
  ThermometerSun,
  TrendingDown,
  TrendingUp,
  Zap,
  ZapOff,
  type LucideIcon,
} from 'lucide-react';
import type { BuildingId, EventId, ResearchId } from '../../game/types.ts';

export const BUILDING_ICONS: Record<BuildingId, LucideIcon> = {
  solar: Sun,
  miner: Pickaxe,
  server: Server,
  optimizer: BrainCircuit,
  reactor: Atom,
  qcore: Cpu,
};

export const RESEARCH_ICONS: Record<ResearchId, LucideIcon> = {
  quantumAlgo: Orbit,
  dataCompression: Layers,
  nitrogenCooling: Snowflake,
  neuroFirewall: ShieldCheck,
  autoBroker: Bot,
  grapheneCells: BatteryCharging,
  shadowLedger: Landmark,
  swarmMind: Network,
  coldFusion: Radiation,
  syndicateProtocol: Crown,
  singularity: Sparkles,
  orbitalMirrors: Satellite,
};

export const EVENT_ICONS: Record<EventId, LucideIcon> = {
  hack: Bug,
  solarFlare: Zap,
  taxAudit: Receipt,
  geoStorm: CloudLightning,
  dataBoom: TrendingUp,
  dataCrash: TrendingDown,
  cryptoRally: Rocket,
  cryptoWinter: Snowflake,
  heatwave: ThermometerSun,
  sabotage: ZapOff,
  investor: Handshake,
  blackMarket: Ghost,
  blueprintLeak: Fingerprint,
  netGrant: BadgeDollarSign,
  rivalRaid: Swords,
  inflationSpike: Percent,
};
